use std::net::SocketAddr;

use lightai_server::{cert, config::Config, db, history_cleanup, platform_log, repository, routes};

const SERVER_VERSION: &str = env!("CARGO_PKG_VERSION");

const SERVER_CONFIG_TEMPLATE: &str = r#"# LightAI Server configuration.
# Generated by: lightai-server config init

[https]
listen_addr = "0.0.0.0:18443"
cert_path = "./certs/server.crt"
key_path = "./certs/server.key"

[http]
enabled = false
listen_addr = "127.0.0.1:18080"

[web]
dist_dir = "web/dist"

[database]
# SQLite database path.
url = "sqlite://./data/lightai.db"

[metrics]
retention_days = 7
cleanup_interval_hours = 6

[auth.password]
min_length = 12
complexity_required = false
expires_days = 0
force_change_after_reset = true

[auth.session]
ttl_secs = 43200
idle_timeout_secs = 7200
secure_cookie = true

[logs]
dir = "logs"
level = "info"
max_file_bytes = 10485760
retention_files = 5
retention_days = 30
"#;

const CONFIG_HELP: &str = r#"lightai-server config — Configuration file management

USAGE:
    lightai-server config init [PATH] [--force]

EXAMPLES:
    lightai-server config init
    lightai-server config init ./my-server.toml
    lightai-server config init --force
"#;

const CERT_HELP: &str = r#"lightai-server cert — Certificate management

USAGE:
    lightai-server cert init --host <IP_OR_DNS> --out <DIR>
    lightai-server cert fingerprint --file <PATH>
    lightai-server cert setup-token

EXAMPLES:
    lightai-server cert init --host 172.19.168.153 --out ./certs
    lightai-server cert init --host lightai.example.local --out /opt/lightai/certs
    lightai-server cert fingerprint --file ./certs/ca.crt
    lightai-server cert setup-token
"#;

const SERVER_HELP: &str = r#"lightai-server — LightAI GPU Model Management Platform Server

USAGE:
    lightai-server [--config <PATH>] [SUBCOMMAND]

SUBCOMMANDS:
    cert        Certificate generation and management
    config      Configuration file management
    collector   GPU collector registry management
    --reset-password <USERNAME> <PASSWORD>
                Reset a local user's password from the server host
    --help      Show this help message
    --version   Show version information

STARTUP:
    Without a subcommand, starts the HTTP/HTTPS server.
    Run scripts/init-local.sh or scripts/init-server.sh first to generate
    certificates and configuration.

CONFIGURATION:
    --config <PATH>        Path to server TOML config file.
    LIGHTAI_SERVER_CONFIG  Environment variable fallback.
    Default config path:   /etc/lightai/lightai-server.toml
"#;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    rustls::crypto::ring::default_provider().install_default()
        .expect("rustls ring crypto provider initialization failed");
    let args: Vec<String> = std::env::args().collect();
    let (subcommand, cli_config_path, sub_idx) = parse_cli(&args);

    if let Some(cmd) = subcommand {
        match cmd.as_str() {
            "--help" | "-h" => {
                println!("{SERVER_HELP}");
                return Ok(());
            }
            "--version" | "-V" => {
                println!("lightai-server {SERVER_VERSION}");
                return Ok(());
            }
            "--reset-password" => {
                let (user, pass) = extract_positional_args(&args, "--reset-password", 2);
                let config = load_server_config(cli_config_path.as_deref())?;
                config.validate_auth()?;
                let pool = db::connect(&config.database_url).await?;
                repository::reset_user_password(
                    &pool, &user, &pass, config.password_policy.clone(),
                )
                .await?;
                println!("password reset completed for user {}", user);
                return Ok(());
            }
            "config" => {
                return handle_config_cmd(&args);
            }
            "collector" => {
                return handle_collector_cmd(&args, sub_idx, cli_config_path.as_deref()).await;
            }
            "cert" => {
                return handle_cert_cmd(&args, sub_idx).await;
            }
            other => {
                eprintln!("unknown subcommand: {other}");
                eprintln!("try: lightai-server --help");
                std::process::exit(1);
            }
        }
    }

    // ── Server mode ──
    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));
    tracing_subscriber::fmt()
        .with_env_filter(env_filter)
        .init();

    let config = load_server_config(cli_config_path.as_deref())?;
    config.validate_auth()?;

    if !config.has_listener() {
        eprintln!("ERROR: No listener configured.");
        eprintln!("Set [https] or [http] in your config file, or run:");
        eprintln!("  scripts/init-local.sh   (local development)");
        eprintln!("  scripts/init-server.sh  (deployment)");
        std::process::exit(1);
    }

    platform_log::set_global(config.log_policy.clone());
    let pool = db::connect(&config.database_url).await?;
    history_cleanup::spawn_cleanup_task(
        pool.clone(),
        config.metrics_retention_days,
        config.history_cleanup_interval_hours,
    );

    let app = routes::app_with_web(
        pool,
        config.password_policy.clone(),
        config.session_policy.clone(),
        config.web_dist_dir.clone(),
        config.setup_token.clone(),
    );

    // Spawn optional HTTP plaintext listener on 127.0.0.1 for troubleshooting.
    if config.http.enabled {
        let http_addr: SocketAddr = config.http.listen_addr.parse()?;
        let http_app = app.clone();
        tokio::spawn(async move {
            let listener = tokio::net::TcpListener::bind(http_addr).await.unwrap();
            tracing::info!(addr = %http_addr, "HTTP listener (local troubleshooting only)");
            axum::serve(listener, http_app).await.unwrap();
        });
    }

    if let Some(https) = &config.https {
        let tls_cfg = load_tls_config(https)?;
        let https_addr: SocketAddr = https.listen_addr.parse()?;
        tracing::info!(
            service = "server",
            listen_addr = %https_addr,
            database_url = %config.database_url,
            "starting lightai server (HTTPS)"
        );
        axum_server::bind_rustls(https_addr, tls_cfg)
            .serve(app.into_make_service())
            .await?;
        // If HTTPS is the primary listener, park main task after TLS server completes.
    } else if config.http.enabled {
        // HTTP-only mode: keep main task alive while spawned HTTP listener runs.
        std::future::pending::<()>().await;
    }

    Ok(())
}

fn load_tls_config(https: &lightai_server::config::HttpsConfig) -> anyhow::Result<axum_server::tls_rustls::RustlsConfig> {
    use rustls_pemfile::{certs, pkcs8_private_keys};
    use std::io::BufReader;

    let cert_file = std::fs::File::open(&https.cert_path)
        .map_err(|e| anyhow::anyhow!("cannot open cert file '{}': {e}", https.cert_path))?;
    let key_file = std::fs::File::open(&https.key_path)
        .map_err(|e| anyhow::anyhow!("cannot open key file '{}': {e}", https.key_path))?;

    let cert_chain: Vec<rustls::pki_types::CertificateDer> = certs(&mut BufReader::new(cert_file))
        .collect::<Result<Vec<_>, _>>()?;
    let key = pkcs8_private_keys(&mut BufReader::new(key_file))
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .next()
        .ok_or_else(|| anyhow::anyhow!("no private key found in {}", https.key_path))?;

    let mut config = rustls::ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(cert_chain, rustls::pki_types::PrivateKeyDer::Pkcs8(key))?;
    config.alpn_protocols = vec![b"h2".to_vec(), b"http/1.1".to_vec()];

    Ok(axum_server::tls_rustls::RustlsConfig::from_config(config.into()))
}

// ── cert subcommand ──

async fn handle_cert_cmd(args: &[String], sub_idx: usize) -> anyhow::Result<()> {
    let cmd_idx = sub_idx + 1;
    if args.len() <= cmd_idx {
        eprintln!("{CERT_HELP}");
        std::process::exit(1);
    }
    match args[cmd_idx].as_str() {
        "--help" | "-h" => {
            println!("{CERT_HELP}");
            Ok(())
        }
        "init" => {
            let host = extract_flag_value(args, "--host").unwrap_or_else(|| {
                eprintln!("usage: lightai-server cert init --host <IP_OR_DNS> --out <DIR>");
                std::process::exit(1);
            });
            let out = extract_flag_value(args, "--out").unwrap_or_else(|| "./certs".to_string());
            let out_dir = std::path::Path::new(&out);
            std::fs::create_dir_all(out_dir)?;

            let is_ip = host.parse::<std::net::IpAddr>().is_ok();
            let (hosts, ips): (Vec<String>, Vec<String>) = if is_ip {
                (vec!["localhost".to_string()], vec![host.clone()])
            } else {
                (vec![host.clone()], vec!["127.0.0.1".to_string()])
            };

            let ca = cert::generate_ca()?;
            cert::write_private(&out_dir.join("ca.key"), &ca.ca_key_pem)?;
            std::fs::write(out_dir.join("ca.crt"), &ca.ca_cert_pem)?;

            let server = cert::generate_server_cert(&ca.ca_cert_pem, &ca.ca_key_pem, &hosts, &ips)?;
            cert::write_private(&out_dir.join("server.key"), &server.key_pem)?;
            std::fs::write(out_dir.join("server.crt"), &server.cert_pem)?;
            // server.crt should include CA cert so clients only need ca.crt + server.crt
            let chain = format!("{}\n{}", server.cert_pem.trim_end(), ca.ca_cert_pem.trim_end());
            std::fs::write(out_dir.join("server.crt"), &chain)?;

            println!("Certificates generated in {}", out_dir.display());
            println!("  CA fingerprint  SHA256:{}", ca.ca_fingerprint);
            println!("  CA cert         {}", out_dir.join("ca.crt").display());
            println!("  CA key          {}", out_dir.join("ca.key").display());
            println!("  Server cert     {}", out_dir.join("server.crt").display());
            println!("  Server key      {}", out_dir.join("server.key").display());
            println!();
            println!("WARNING: ca.key and server.key are sensitive — do NOT distribute.");
            println!("ca.crt can be distributed to Agent machines.");
            Ok(())
        }
        "fingerprint" => {
            let file = extract_flag_value(args, "--file").unwrap_or_else(|| {
                eprintln!("usage: lightai-server cert fingerprint --file <PATH>");
                std::process::exit(1);
            });
            let der = std::fs::read(&file)?;
            // Try PEM first, fall back to raw DER.
            let mut reader = std::io::BufReader::new(std::fs::File::open(&file)?);
            let mut certs = rustls_pemfile::certs(&mut reader);
            let fp = if let Some(Ok(c)) = certs.next() {
                cert::sha256_hex(c.as_ref())
            } else {
                cert::sha256_hex(&der)
            };
            println!("{fp}");
            Ok(())
        }
        "setup-token" => {
            let token = generate_setup_token();
            println!("{token}");
            Ok(())
        }
        other => {
            eprintln!("unknown cert subcommand: {other}");
            eprintln!("{CERT_HELP}");
            std::process::exit(1);
        }
    }
}

fn generate_setup_token() -> String {
    use rand::Rng;
    let mut rng = rand::rng();
    let bytes: [u8; 16] = rng.random();
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

// ── collector subcommand ──

const COLLECTOR_HELP: &str = r#"lightai-server collector — GPU collector registry management

USAGE:
    lightai-server collector inspect  --dir <PATH> | --root <PATH>
    lightai-server collector sync     --root <PATH>
    lightai-server collector register --dir <PATH>

SUBCOMMANDS:
    inspect  Read collector metadata and compute script hashes.
             Does NOT write to the database.
    sync     Scan a collector root directory and upsert all valid collector
             subdirectories into the Server registry.
    register Upsert a single collector directory into the Server registry.

EXAMPLES:
    lightai-server --config lightai-server.toml collector sync --root ./collectors/gpu
    lightai-server --config lightai-server.toml collector register --dir ./collectors/gpu/nvidia-wsl

NOTES:
    - Uses the Server database (same as the running Server).
    - Only reads collector.toml + computes script hashes; does NOT execute scripts.
    - Same id+version → upsert (metadata + hash updated, enabled preserved).
    - New collectors default to enabled=true.
    - Does NOT require a running Server process.
"#;

async fn handle_collector_cmd(args: &[String], sub_idx: usize, cli_config_path: Option<&str>) -> anyhow::Result<()> {
    let cmd_idx = sub_idx + 1;
    if args.len() <= cmd_idx {
        eprintln!("missing collector subcommand (inspect | sync | register)");
        eprintln!("try: lightai-server collector --help");
        std::process::exit(1);
    }

    let collector_cmd = args[cmd_idx].as_str();
    if collector_cmd == "--help" || collector_cmd == "-h" {
        println!("{COLLECTOR_HELP}");
        return Ok(());
    }

    match collector_cmd {
        "sync" => {
            let root = extract_flag_value(args, "--root");
            let Some(root) = root else {
                eprintln!("usage: lightai-server collector sync --root <PATH>");
                std::process::exit(1);
            };
            let config = load_server_config(cli_config_path)?;
            let pool = db::connect(&config.database_url).await?;
            match lightai_server::collector_cli::sync_root(&pool, std::path::Path::new(&root)).await
            {
                Ok(outcomes) => {
                    for o in &outcomes {
                        match o {
                            lightai_server::collector_cli::RegisterOutcome::Registered {
                                id, version, discover_sha256, metrics_sha256,
                            } => {
                                println!(
                                    "registered  {id} v{version}  discover={} metrics={}",
                                    &discover_sha256[..discover_sha256.len().min(12)],
                                    &metrics_sha256[..metrics_sha256.len().min(12)],
                                );
                            }
                            lightai_server::collector_cli::RegisterOutcome::Updated {
                                id, version, discover_sha256, metrics_sha256,
                            } => {
                                println!(
                                    "updated     {id} v{version}  discover={} metrics={}",
                                    &discover_sha256[..discover_sha256.len().min(12)],
                                    &metrics_sha256[..metrics_sha256.len().min(12)],
                                );
                            }
                            lightai_server::collector_cli::RegisterOutcome::Skipped { dir, reason } => {
                                println!("skipped     {dir}  ({reason})");
                            }
                        }
                    }
                    println!("done — {} collector(s) processed", outcomes.len());
                }
                Err(e) => {
                    eprintln!("sync failed: {e:#}");
                    std::process::exit(1);
                }
            }
        }
        "inspect" => {
            if let Some(dir) = extract_flag_value(args, "--dir") {
                match lightai_server::collector_cli::inspect_one(std::path::Path::new(&dir)) {
                    Ok(r) => {
                        println!("{}", serde_json::to_string_pretty(&r).unwrap_or_else(|_| format!("{r:?}")));
                    }
                    Err(e) => {
                        eprintln!("inspect failed: {e:#}");
                        std::process::exit(1);
                    }
                }
            } else if let Some(root) = extract_flag_value(args, "--root") {
                match lightai_server::collector_cli::inspect_root(std::path::Path::new(&root)) {
                    Ok(results) => {
                        println!(
                            "{}",
                            serde_json::to_string_pretty(&results)
                                .unwrap_or_else(|_| format!("{results:?}"))
                        );
                    }
                    Err(e) => {
                        eprintln!("inspect failed: {e:#}");
                        std::process::exit(1);
                    }
                }
            } else {
                eprintln!("usage: lightai-server collector inspect --dir <PATH> | --root <PATH>");
                std::process::exit(1);
            }
        }
        "register" => {
            let dir = extract_flag_value(args, "--dir");
            let Some(dir) = dir else {
                eprintln!("usage: lightai-server collector register --dir <PATH>");
                std::process::exit(1);
            };
            let config = load_server_config(cli_config_path)?;
            let pool = db::connect(&config.database_url).await?;
            match lightai_server::collector_cli::register_one(&pool, std::path::Path::new(&dir)).await
            {
                Ok(outcome) => match outcome {
                    lightai_server::collector_cli::RegisterOutcome::Registered {
                        id, version, discover_sha256, metrics_sha256,
                    }
                    | lightai_server::collector_cli::RegisterOutcome::Updated {
                        id, version, discover_sha256, metrics_sha256,
                    } => {
                        println!(
                            "ok  {id} v{version}  discover={} metrics={}",
                            &discover_sha256[..discover_sha256.len().min(12)],
                            &metrics_sha256[..metrics_sha256.len().min(12)],
                        );
                    }
                    lightai_server::collector_cli::RegisterOutcome::Skipped { dir, reason } => {
                        eprintln!("skipped  {dir}  ({reason})");
                        std::process::exit(1);
                    }
                },
                Err(e) => {
                    eprintln!("register failed: {e:#}");
                    std::process::exit(1);
                }
            }
        }
        other => {
            eprintln!("unknown collector subcommand: {other}");
            eprintln!("try: lightai-server --config <PATH> collector --help");
            eprintln!("  or: lightai-server collector --help");
            std::process::exit(1);
        }
    }
    Ok(())
}

// ── config subcommand ──

fn handle_config_cmd(args: &[String]) -> anyhow::Result<()> {
    if args.len() < 3 || args[2] == "--help" || args[2] == "-h" {
        println!("{CONFIG_HELP}");
        return Ok(());
    }
    match args[2].as_str() {
        "init" => {
            if args.get(3).map(String::as_str) == Some("--help") || args.get(3).map(String::as_str) == Some("-h") {
                println!("{CONFIG_HELP}");
                return Ok(());
            }
            let mut path: Option<&str> = None;
            let mut force = false;
            for arg in args.iter().skip(3) {
                match arg.as_str() {
                    "--force" => force = true,
                    other if !other.starts_with('-') => path = Some(other),
                    _ => {}
                }
            }
            let dest_path = path.unwrap_or("lightai-server.toml");
            let dest = std::path::Path::new(dest_path);
            if let Some(parent) = dest.parent() {
                if !parent.as_os_str().is_empty() {
                    std::fs::create_dir_all(parent)?;
                }
            }
            if dest.exists() && !force {
                anyhow::bail!("'{}' already exists. Use --force to overwrite.", dest.display());
            }
            std::fs::write(dest, SERVER_CONFIG_TEMPLATE)?;
            println!("Config template written to '{}'", dest.display());
            Ok(())
        }
        other => {
            eprintln!("unknown config subcommand: {other}");
            eprintln!("try: lightai-server config --help");
            std::process::exit(1);
        }
    }
}

// ── CLI helpers ──

/// Parse CLI args into (subcommand, config_path, subcommand_index).
fn parse_cli(args: &[String]) -> (Option<String>, Option<String>, usize) {
    if args.len() < 2 {
        return (None, None, 1);
    }
    let mut idx = 1;
    let mut config_path: Option<String> = None;
    if args[idx] == "--config" {
        if args.len() > idx + 1 {
            config_path = Some(args[idx + 1].clone());
            idx += 2;
        } else {
            eprintln!("error: --config requires a path");
            std::process::exit(1);
        }
    }
    if idx < args.len() {
        let sub = args[idx].clone();
        return (Some(sub), config_path, idx);
    }
    (None, config_path, idx)
}

fn extract_flag_value(args: &[String], flag: &str) -> Option<String> {
    for i in 0..args.len() {
        if args[i] == flag {
            return args.get(i + 1).cloned();
        }
    }
    None
}

fn extract_positional_args(args: &[String], flag: &str, count: usize) -> (String, String) {
    for i in 0..args.len() {
        if args[i] == flag {
            if args.len() <= i + count {
                eprintln!("usage: lightai-server --reset-password <USERNAME> <PASSWORD>");
                std::process::exit(1);
            }
            return (args[i + 1].clone(), args[i + 2].clone());
        }
    }
    eprintln!("usage: lightai-server --reset-password <USERNAME> <PASSWORD>");
    std::process::exit(1);
}

fn load_server_config(explicit_path: Option<&str>) -> anyhow::Result<Config> {
    if let Some(path) = explicit_path {
        if path.is_empty() {
            anyhow::bail!("--config requires a non-empty path");
        }
        return Config::from_file(path);
    }
    Config::load()
}
