use std::net::SocketAddr;

use lightai_server::{config::Config, db, history_cleanup, platform_log, repository, routes};

const SERVER_VERSION: &str = env!("CARGO_PKG_VERSION");

const SERVER_CONFIG_TEMPLATE: &str = r#"# LightAI Server configuration.
# Generated by: lightai-server config init

[server]
# Listen address.  Use 0.0.0.0:10080 to accept external connections.
listen_addr = "0.0.0.0:10080"

[database]
# SQLite database path.
# Relative paths are resolved against the process CWD.\n# With systemd WorkingDirectory=/opt/lightai, this becomes /opt/lightai/data/lightai.db.
url = "sqlite://./data/lightai.db"

[metrics]
# Days of historical metric samples to retain (minimum 1).
retention_days = 7
# How often to run the cleanup task, in hours (minimum 1).
cleanup_interval_hours = 6

# ── Authentication ──
[auth.password]
min_length = 12
complexity_required = false
# 0 disables password expiration.
expires_days = 0
force_change_after_reset = true

[auth.session]
ttl_secs = 43200
idle_timeout_secs = 7200
# Set true when serving Web/API over HTTPS.
secure_cookie = false

# ── Logging ──
[logs]
dir = "logs"
level = "info"
max_file_bytes = 10485760
retention_files = 5
retention_days = 30

# ── Notes ──
# - First admin is created through the Web setup page (empty database → auto-redirect).
# - Forgot password? Run on the server host:
#     lightai-server --reset-password <USERNAME> <PASSWORD>
# - Web and API should be same-origin or behind a single reverse proxy.
# - Copy this file to /etc/lightai/lightai-server.toml for production deployment:
#     sudo lightai-server config init /etc/lightai/lightai-server.toml
"#;

const CONFIG_HELP: &str = r#"lightai-server config — Configuration file management

USAGE:
    lightai-server config init [PATH] [--force]

SUBCOMMANDS:
    init    Generate a LightAI Server config template.
            If PATH is omitted, writes ./lightai-server.toml
            in the current working directory.
            Use --force to overwrite an existing file.

EXAMPLES:
    lightai-server config init
    lightai-server config init ./my-server.toml
    lightai-server config init /etc/lightai/lightai-server.toml
    lightai-server config init --force
    lightai-server config init /etc/lightai/lightai-server.toml --force
"#;

const SERVER_HELP: &str = r#"lightai-server — LightAI GPU Model Management Platform Server

USAGE:
    lightai-server [OPTIONS]

OPTIONS:
    --help       Show this help message
    --version    Show version information
    --config <PATH>
                Path to LightAI Server config TOML file.
                Env: LIGHTAI_SERVER_CONFIG.
                Default: /etc/lightai/lightai-server.toml.
                Falls back to built-in defaults if the file does not exist.
    --reset-password <USERNAME> <PASSWORD>
                Reset a local user's password from the server host

SUBCOMMANDS:
    config      Configuration file management
                lightai-server config init [PATH] [--force]
    collector   GPU collector registry management
                lightai-server collector inspect  --dir <PATH> | --root <PATH>
                lightai-server collector sync     --root <PATH>
                lightai-server collector register --dir <PATH>

DESCRIPTION:
    LightAI Server is the platform control plane. Responsibilities:
    - Agent registration, heartbeat auth, config distribution
    - Node/GPU status management and historical metrics storage
    - Runtime / Model / Model File / Instance / Trash management
    - Platform logging and audit

CONFIGURATION:
    Environment variable: LIGHTAI_SERVER_CONFIG=<path>
    Empty databases enter Web setup mode for first-admin creation
    Default: embedded defaults (listen 0.0.0.0:10080, SQLite ./data/lightai.db)
"#;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // ── CLI argument handling ──
    let args: Vec<String> = std::env::args().collect();
    if args.len() >= 2 {
        match args[1].as_str() {
            "--help" | "-h" => {
                println!("{SERVER_HELP}");
                return Ok(());
            }
            "--version" | "-V" => {
                println!("lightai-server {SERVER_VERSION}");
                return Ok(());
            }
            "--reset-password" => {
                if args.len() != 4 {
                    eprintln!("usage: lightai-server --reset-password <USERNAME> <PASSWORD>");
                    std::process::exit(1);
                }
                let config = Config::load()?;
                config.validate_auth()?;
                let pool = db::connect(&config.database_url).await?;
                repository::reset_user_password(
                    &pool,
                    &args[2],
                    &args[3],
                    config.password_policy.clone(),
                )
                .await?;
                println!("password reset completed for user {}", args[2]);
                return Ok(());
            }
            "config" => {
                return handle_config_cmd(&args);
            }
            "collector" => {
                return handle_collector_cmd(&args).await;
            }
            other => {
                eprintln!("unknown option: {other}");
                eprintln!("try: lightai-server --help");
                std::process::exit(1);
            }
        }
    }

    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let config = Config::load()?;
    config.validate_auth()?;
    platform_log::set_global(config.log_policy.clone());
    platform_log::append(&config.log_policy, "server.log", "info", "Server starting").await?;
    let listen_addr: SocketAddr = config.listen_addr.parse()?;
    let pool = db::connect(&config.database_url).await?;
    history_cleanup::spawn_cleanup_task(
        pool.clone(),
        config.metrics_retention_days,
        config.history_cleanup_interval_hours,
    );
    let listener = tokio::net::TcpListener::bind(listen_addr).await?;

    tracing::info!(
        service = "server",
        listen_addr = %listen_addr,
        database_url = %config.database_url,
        metrics_retention_days = config.metrics_retention_days,
        history_cleanup_interval_hours = config.history_cleanup_interval_hours,
        "starting lightai server"
    );

    axum::serve(
        listener,
        routes::app_with_auth_policies(pool, config.password_policy, config.session_policy),
    )
    .await?;
    Ok(())
}

// ── config subcommand ──

fn handle_config_cmd(args: &[String]) -> anyhow::Result<()> {
    if args.len() < 3 || args[2] == "--help" || args[2] == "-h" {
        println!("{CONFIG_HELP}");
        return Ok(());
    }
    match args[2].as_str() {
        "init" => {
            if args.get(3).map(String::as_str) == Some("--help")
                || args.get(3).map(String::as_str) == Some("-h")
            {
                println!("{CONFIG_HELP}");
                return Ok(());
            }
            let mut path: Option<&str> = None;
            let mut force = false;
            for arg in args.iter().skip(3) {
                match arg.as_str() {
                    "--force" => force = true,
                    other if !other.starts_with('-') => path = Some(other),
                    _ => {}
                }
            }
            let dest_path = path.unwrap_or("lightai-server.toml");
            let dest = std::path::Path::new(dest_path);
            if let Some(parent) = dest.parent() {
                if !parent.as_os_str().is_empty() {
                    std::fs::create_dir_all(parent)?;
                }
            }
            if dest.exists() && !force {
                anyhow::bail!(
                    "'{}' already exists. Use --force to overwrite.",
                    dest.display()
                );
            }
            std::fs::write(dest, SERVER_CONFIG_TEMPLATE)?;
            println!("Config template written to '{}'", dest.display());
            Ok(())
        }
        other => {
            eprintln!("unknown config subcommand: {other}");
            eprintln!("try: lightai-server config --help");
            std::process::exit(1);
        }
    }
}

// ── collector subcommand ──

const COLLECTOR_HELP: &str = r#"lightai-server collector — GPU collector registry management

USAGE:
    lightai-server collector inspect  --dir <PATH> | --root <PATH>
    lightai-server collector sync     --root <PATH>
    lightai-server collector register --dir <PATH>

SUBCOMMANDS:
    inspect  Read collector metadata and compute script hashes.
             Does NOT write to the database.
    sync     Scan a collector root directory and upsert all valid collector
             subdirectories into the Server registry.
    register Upsert a single collector directory into the Server registry.

EXAMPLES:
    # Batch-register all collectors under a root:
    lightai-server collector sync --root /opt/lightai/collectors/gpu

    # Register/update one specific collector:
    lightai-server collector register --dir /opt/lightai/collectors/gpu/nvidia-wsl

NOTES:
    - Uses the Server database (same as the running Server).
    - Only reads collector.toml + computes script hashes; does NOT execute scripts.
    - Same id+version → upsert (metadata + hash updated, enabled preserved).
    - New collectors default to enabled=true.
    - Does NOT require a running Server process.
"#;

async fn handle_collector_cmd(args: &[String]) -> anyhow::Result<()> {
    if args.len() < 3 {
        eprintln!("missing collector subcommand (inspect | sync | register)");
        eprintln!("try: lightai-server collector --help  (not yet supported)");
        std::process::exit(1);
    }

    match args[2].as_str() {
        "sync" => {
            let root = extract_flag_value(args, "--root");
            let Some(root) = root else {
                eprintln!("usage: lightai-server collector sync --root <PATH>");
                std::process::exit(1);
            };
            let config = Config::load()?;
            let pool = db::connect(&config.database_url).await?;
            match lightai_server::collector_cli::sync_root(&pool, std::path::Path::new(&root)).await
            {
                Ok(outcomes) => {
                    for o in &outcomes {
                        match o {
                            lightai_server::collector_cli::RegisterOutcome::Registered {
                                id,
                                version,
                                discover_sha256,
                                metrics_sha256,
                            } => {
                                println!(
                                    "registered  {id} v{version}  discover={} metrics={}",
                                    &discover_sha256[..discover_sha256.len().min(12)],
                                    &metrics_sha256[..metrics_sha256.len().min(12)],
                                );
                            }
                            lightai_server::collector_cli::RegisterOutcome::Updated {
                                id,
                                version,
                                discover_sha256,
                                metrics_sha256,
                            } => {
                                println!(
                                    "updated     {id} v{version}  discover={} metrics={}",
                                    &discover_sha256[..discover_sha256.len().min(12)],
                                    &metrics_sha256[..metrics_sha256.len().min(12)],
                                );
                            }
                            lightai_server::collector_cli::RegisterOutcome::Skipped {
                                dir,
                                reason,
                            } => {
                                println!("skipped     {dir}  ({reason})");
                            }
                        }
                    }
                    println!("done — {} collector(s) processed", outcomes.len());
                }
                Err(e) => {
                    eprintln!("sync failed: {e:#}");
                    std::process::exit(1);
                }
            }
        }
        "inspect" => {
            if let Some(dir) = extract_flag_value(args, "--dir") {
                match lightai_server::collector_cli::inspect_one(std::path::Path::new(&dir)) {
                    Ok(r) => {
                        println!(
                            "{}",
                            serde_json::to_string_pretty(&r).unwrap_or_else(|_| format!("{r:?}"))
                        );
                    }
                    Err(e) => {
                        eprintln!("inspect failed: {e:#}");
                        std::process::exit(1);
                    }
                }
            } else if let Some(root) = extract_flag_value(args, "--root") {
                match lightai_server::collector_cli::inspect_root(std::path::Path::new(&root)) {
                    Ok(results) => {
                        println!(
                            "{}",
                            serde_json::to_string_pretty(&results)
                                .unwrap_or_else(|_| { format!("{results:?}") })
                        );
                    }
                    Err(e) => {
                        eprintln!("inspect failed: {e:#}");
                        std::process::exit(1);
                    }
                }
            } else {
                eprintln!("usage: lightai-server collector inspect --dir <PATH> | --root <PATH>");
                std::process::exit(1);
            }
        }
        "register" => {
            let dir = extract_flag_value(args, "--dir");
            let Some(dir) = dir else {
                eprintln!("usage: lightai-server collector register --dir <PATH>");
                std::process::exit(1);
            };
            let config = Config::load()?;
            let pool = db::connect(&config.database_url).await?;
            match lightai_server::collector_cli::register_one(&pool, std::path::Path::new(&dir))
                .await
            {
                Ok(outcome) => match outcome {
                    lightai_server::collector_cli::RegisterOutcome::Registered {
                        id,
                        version,
                        discover_sha256,
                        metrics_sha256,
                    }
                    | lightai_server::collector_cli::RegisterOutcome::Updated {
                        id,
                        version,
                        discover_sha256,
                        metrics_sha256,
                    } => {
                        println!(
                            "ok  {id} v{version}  discover={} metrics={}",
                            &discover_sha256[..discover_sha256.len().min(12)],
                            &metrics_sha256[..metrics_sha256.len().min(12)],
                        );
                    }
                    lightai_server::collector_cli::RegisterOutcome::Skipped { dir, reason } => {
                        eprintln!("skipped  {dir}  ({reason})");
                        std::process::exit(1);
                    }
                },
                Err(e) => {
                    eprintln!("register failed: {e:#}");
                    std::process::exit(1);
                }
            }
        }
        "--help" | "-h" => {
            println!("{COLLECTOR_HELP}");
        }
        other => {
            eprintln!("unknown collector subcommand: {other}");
            eprintln!("try: lightai-server collector --help");
            std::process::exit(1);
        }
    }
    Ok(())
}

fn extract_flag_value(args: &[String], flag: &str) -> Option<String> {
    for i in 0..args.len() {
        if args[i] == flag {
            return args.get(i + 1).cloned();
        }
    }
    None
}
